name: $(majorVersion).$(minorVersion)

variables:
  majorVersion: $(Year:yy)
  minorVersion: $[counter(variables['majorVersion'], 1)]
  buildConfiguration: Release
  appName: Iface.Oik.SvgPlayground
  archiveName: $(appName).$(Build.BuildNumber)
  github: alexeid1337


trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: windows-latest
    steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '-c $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: false
        arguments: '-c $(BuildConfiguration) -r win-x64 --self-contained false /p:CopyOutputSymbolsToPublishDirectory=false /p:PublishSingleFile=true -o $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true
        modifyOutputPath: false

    - script: 'RENAME a.zip $(archiveName).zip'
      displayName: Rename archive
      workingDirectory: $(Build.ArtifactStagingDirectory)

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: $(appName)


- stage: Deploy
  dependsOn:
  - Build
  jobs:
  - deployment: Deploy
    pool:
      vmImage: windows-latest
    environment: GitHub
    strategy:
      runOnce:
        deploy:
          steps:
          - task: GithubRelease@0
            inputs:
              gitHubConnection: $(github)
              repositoryName: $(github)/$(appName)
              tagSource: manual
              tag: $(Build.BuildNumber)