name: master

on: 
  push:
    branches:
      - master
    
env:
   APP_NAME: Iface.Oik.SvgPlayground

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Build
      run: dotnet build -c Release

    - name: Prepare version number
      id: version
      run: echo "::set-output name=id::$(date +'%y').${{github.run_number}}"

    - name: Prepare release names
      id: release
      run: echo "::set-output name=release::${{env.APP_NAME}}.${{steps.version.outputs.id}}.zip"

    - name: Publish
      run: dotnet publish -c Release -r win-x64 --self-contained false /p:CopyOutputSymbolsToPublishDirectory=false /p:PublishSingleFile=true -o dist
        
    - name: Make archive
      run: 7z a ${{steps.release.outputs.release}} ./dist/*
      
    - name: Create Github Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{steps.version.outputs.id}}
        release_name: ${{env.APP_NAME}} ${{steps.version.outputs.id}}
        
    - name: Upload Github Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./${{steps.release.outputs.release}}
        asset_name: ${{steps.release.outputs.release}}
        asset_content_type: application/zip